language: go

stages:
  - build
  - publish

jobs:
include:
  - stage: build 
    image: go:latest  
    script:
      - go build
  - stage: publish 
    image: node:latest
    script:
      - npm login --registry=https://npm.pkg.github.com/
      - npm publish
